name: hcbp-lint

on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'examples/**/*.tf'
      - 'examples/**/*.tfvars'

jobs:
  lint-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch master branch
        run: git fetch origin master:master

      - name: Lint Terraform Examples
        uses: Lance52259/hcbp-scripts-lint@v2.2.0
        with:
          directory: 'examples'
          fail-on-error: 'true'
          exclude-paths: '*.md,*.txt,*.json,*.yml,*.yaml'
          changed-files-only: 'true'
          base-ref: 'master'
